### ISSUE TITLE
refute does not work

### ISSUE THREAD

**Issue by mblumtritt** [hsbt/minitest-power_assert#5]
The line https://github.com/hsbt/minitest-power_assert/blame/master/lib/minitest/power_assert.rb#L21 results in a call to `#assert` with an Array. This means to call
```ruby
assert true
```
That means that `#refute` does never work like expected.

**Comment by hsbt** [comment]
@mblumtritt I fixed at b803500. Can you try this revision?

**Comment by mblumtritt** [comment]
Oh - I already made a pull request: https://github.com/hsbt/minitest-power_assert/pull/6

**Comment by mblumtritt** [comment]
(closed because of using wrong button)

**Comment by hsbt** [comment]
I merged your pull request and bump version to 0.2.0

**Comment by mblumtritt** [comment]
Cool! Thanks!
