### ISSUE TITLE
minitest does not show correct error message

### ISSUE THREAD

**Issue by yskkin** [hsbt/minitest-power_assert#9]
# Step to reproduce
1. Set up `test.rb`
```
require "minitest/autorun"
require 'minitest/power_assert'

class TestPowerAssert < Minitest::Test
  def test_power_assert_failed
    assert { "0".class == "3".to_i.times.map {|i| i + 1 }.class }
  end
end
```

2. execute `bundle exec ruby test.rb`

# Expected behavior
Error message with detailed inspection is shown.

# Actual behavior
Got following output:
```
Run options: --seed 19742

# Running:

F

Finished in 0.012801s, 78.1189 runs/s, 78.1189 assertions/s.

  1) Failure:
TestPowerAssert#test_power_assert_failed [test.rb:6]:
      exit_code = Minitest.run ARGV


1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

# Versions
  * ruby 2.3.3p222
  * bundler (1.15.0)
  * minitest (5.10.2)
  * minitest-power_assert (0.2.0)
  * power_assert (1.0.2)

**Comment by mblumtritt** [comment]
Checked with same Ruby version, power_assert-1.0.2, minitest-power_assert-0.2.0, minitest-5.10.2 and works well 🤔
I did not use bundler. But also checked with Ruby 2.4.1 ok. All on MacOS.
What's the diff to your env?

**Comment by yskkin** [comment]
With `bundle install --path vendor/bundle` to disable shared gem, it works as expected.
But even if I uninstall and reinstall `minitest`, `power_assert`, `minitest-power_assert` to system global, nothing changes. 😕

**Comment by yskkin** [comment]
I'm using rbenv installed with homebrew on macOS.
`bundle info minitest-power_assert` shows installed path is `/usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/minitest-power_assert-0.2.0`, where /usr/local/opt/rbenv is symlinked.
```
ls -l /usr/local/opt/rbenv
lrwxr-xr-x  1 yskkin  admin  21  8 28  2016 /usr/local/opt/rbenv -> ../Cellar/rbenv/1.0.0
```

When using gem installed system globally,
`PowerAssert::IGNORED_LIB_DIRS` is `{PowerAssert=>
  "/usr/local/Cellar/rbenv/1.0.0/versions/2.3.3/lib/ruby/gems/2.3.0/gems/power_assert-1.0.2/lib"}`
and 
`PowerAssert.app_caller_locations.first.path` is `"/usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/power_assert-1.0.2/lib/power_assert/context.rb`

It seems that `PowerAssert::ignored_file?` cannot handle symlink properly.

**Comment by yskkin** [comment]
Closing since this is an upstream issue.

**Comment by hsbt** [comment]
Thanks to your investigation. I will add dependency for https://github.com/k-tsj/power_assert/issues/18 after releasing to next version of power_assert.
